[package]
name = "faster_poisson"
version = "0.1.0"
edition = "2024"

[dependencies]
ndarray = "0.16.1"
rand = "0.9.2"
rand_xoshiro = "0.7.0"

[dev-dependencies]
criterion = "0.7.0"

[[bench]]
name = "poisson_disk_sampling"
harness = false
